merge commit in Master (#26)
* doc: Update constructor optimization of variable logFormatDate

* chore(release): 0.7.0

* chore(release): 0.7.1

* fix: error with variable logFormatDate in constructor

* chore(release): 0.7.2

* fix: README.md translate to Spanish

* chore(release): 0.7.3

* fix: update README.md translate to Spanish

* chore(release): 0.7.4

* feat: add function parseDate

* chore(release): 0.8.0

* Fix: correction in function parseDate

* chore(release): 0.8.1

* fix: adjust links in documentation

* chore(release): 0.7.3

* chore(release): 0.9.0

* feat: refactoring of the logExecution and LogError function. (Change to writeLog and writeLogError).
- New parameter in the constructor. [name WriteLog and nameWriteLogError].
- Optimization in the way of validating the parameter object that the constructor receives

* chore(release): 0.10.0

* fix: add test for generateRageDate

* chore(release): 0.10.1

* fix: adjust in the documentation

* chore(release): 0.10.2

* fix: travis-ci.org TypeError: u.logExecution is not a function
- at Context.<anonymous> (test/test_clearFolder.js:8:11)
- at Context.<anonymous> (test/test_deleteFile.js:8:11)
and rename function logExecution for writeLog
and rename function logError for writeLogError

* chore(release): 0.10.3

* fix: Update links of /EN to /ES and load homePage in language Spanish

* chore(release): 0.10.4

* fix: Update links fix issue #24

* chore(release): 0.10.5

* fix: Update links fix issue #24 -part#2

* chore(release): 0.10.6

* fix: Update links fix issue #24 -part#3

* chore(release): 0.10.7

* fix: Fixed spelling error in the constructor `folderFormatDate =\= folderFormatDate`

* fix: Fixed spelling error in the constructor `folderFormatDate =\= folderFormatDate` in createFolders

* fix: change const `c` for `constant`

* fix: write head for documentation
- change const `c` for `constant`

* fix: Fixed variables name

* BREAKING CHANGE: Complete change in the structure of the Constructor.
                 - A compiler was implemented to generate the class dynamically.
                 - The getFinalPath function was added
                 - the variable const "c" was changed to "constant"
                 - Update in documentation

* chore(release): 0.10.8

* BREAKING CHANGE: Complete change in the structure of the Constructor.
                 - A compiler was implemented to generate the class dynamically.
                 - The getFinalPath function was added
                 - the variable const "c" was changed to "constant"
                 - Update in documentation

* chore(release): 0.10.9

* BREAKING CHANGE

* chore(release): 0.10.10

* feat(new-version): Refactorization absolute
BREAKING CHANGE: new structure of jsDoc in all function.

* chore(release): 0.11.0

* BREAKING CHANGE: force change of version.

* chore(release): 1.0.1

* feat: compiler automatically generates the index.js file

* chore(release): 1.1.0

* fix: correct minor in test and function CreateFolders

* chore(release): 1.1.1

* fix: Removed console.log in getFinalPath.

* fix: correction variable c for constant

* feat: writeLogError add throw Exception. update test for WriteLogError

* chore(release): 1.2.0

* fix: text formatting

* feat: New function allEqual(). This snippet checks whether all elements of the array are equal.

* feat: New function allEqual(). This snippet checks whether all elements of the array are equal.

* chore(release): 1.3.0

* feat: add test in object of method info()

* fix: correction in constructor params folderAutoDate change for folderWithDate.
- getFinalPath correction path

* feat: completed test for:
- everyOrNone
- getFinalPath
- groupBy
- increaseDays
- _log
- objectToDate

* chore(release): 1.4.0

* fix: removed dependency `imap-simple`.

* chore(release): 1.4.1

* feat: unos detalles pendiente para haerlo un sabado o dimingo add funtionality dayOfYear.js

* feat: refactoring compiler.js - Part 1

* fix: ignore data folder  add command file

* chore(release): 1.5.0

* fix: working in compiler.js create function render documentation

* fix: update compiler.js and add documentation in folder english

* fix: add documentation in folder english

* chore(release): 1.6.0

* fix: add dayOfYear() in class JS-PackTools

* chore(release): 1.6.1

* fix: Update render.js and update documentation

* chore(release): 1.6.2

* feat: add new function renameFiles()

* chore(release): 1.7.0

* fix: Update order to test

* chore(release): 1.7.1

* fiX: delete variable arMethods

* feat: new function capitalLetter.js

* chore(release): 1.9.0

* fix: update function capitalLetter.js

* chore(release): 1.9.1

* fix: debug error, not allowed object date as parameters

* fix: debug error, test logError

* fix: debug error, global.test.js. validate year is outdated year.

* fix: Update Replace "assert.equal" with "assert.strictEqual" [more info](https://github.com/googleapis/gapic-generator/issues/2154)

* fix: debug error, in global.test.js (function differenceDay)

* Update Readme

* chore(deps-dev): bump standard-version from 5.0.2 to 8.0.1

Bumps [standard-version](https://github.com/conventional-changelog/standard-version) from 5.0.2 to 8.0.1.
- [Release notes](https://github.com/conventional-changelog/standard-version/releases)
- [Changelog](https://github.com/conventional-changelog/standard-version/blob/master/CHANGELOG.md)
- [Commits](https://github.com/conventional-changelog/standard-version/compare/v5.0.2...v8.0.1)

Signed-off-by: dependabot[bot] <support@github.com>

* Update Reade

translate all documentation into English

* Create modStart, update parseDate to use modStart

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Diego <andres.dafg@gmail.com>